"""test

Revision ID: 138f1de6babf
Revises: d3c13f54c839
Create Date: 2026-03-03 22:53:09.800477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "138f1de6babf"
down_revision: Union[str, Sequence[str], None] = "d3c13f54c839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("shoppingList", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.String(length=30), nullable=True))

        batch_op.alter_column(
            "user_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )

    op.execute("UPDATE shoppingList SET role = 'owner'")

    with op.batch_alter_table("shoppingList", schema=None) as batch_op:
        batch_op.alter_column(
            "role", existing_type=sa.String(length=30), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shoppingList", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        batch_op.drop_column("role")

    op.create_table(
        "_alembic_tmp_shoppingList",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("user_id", sa.NUMERIC(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("modified", sa.DATETIME(), nullable=False),
        sa.Column("role", sa.VARCHAR(length=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
