"""userid to str

Revision ID: e568604be428
Revises: 138f1de6babf
Create Date: 2026-03-03 23:17:32.837752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e568604be428'
down_revision: Union[str, Sequence[str], None] = '138f1de6babf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingList', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingList', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=100),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
